Add default shard
Attempt to fix
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service io.streamnative.oxia.proto.OxiaClient

Since found this error in the logs:
  rpc error: code = Code(110) desc = oxia: namespace not found
  Failed to add client for shards assignments notifications